### ISSUE TITLE
incompatibilities

### ISSUE THREAD

**Issue by duarm** [TheRedBrain/overhauled-damage#1]
Thanks for making overhauled damage!

Tried to run overhauled-damage in my modpack and found a bunch of incompatibilities, Tested with minimum dependencies:

- Cloth Config V11
- Fabric API
- Overhauled Damage
- Player Animator
- Spell Engine
- Spell Power Attribute
- Stamina Attributes

Incompatibilities found:

- [Zenith](https://modrinth.com/mod/zenith)
- [Balm](https://modrinth.com/mod/balm)(lib)
- [Collective](https://modrinth.com/mod/collective)(lib)
- [Victus](https://modrinth.com/mod/victus)

and probably more, I'll update this when I get the chance to try the other mods.

**Comment by TheRedBrain** [comment]
Thanks for reporting those incompatibilities!

I'll have a look at it
