### ISSUE TITLE
Question About the Tag System for Assigning Damage Types

### ISSUE THREAD

**Issue by InputandOutput** [TheRedBrain/overhauled-damage#2]
Hello TheRedBrain,
Looking in your resources folder to find the necessary tags to assign to custom weapons, I've noticed that there are a lot of tags that are assigned to a particular percentage of damage done as a damage type. I'm wonder that, instead of having a lot of tags to assign specific proportions of damage types, why isn't the option to pass an integer or a double to modify the proportions? It would save the hassle of using a lot of tags and to allow finer control of the proportions for the chosen damage type.

**Comment by TheRedBrain** [comment]
Tags seemed to be the best solution for compatibility and customization. But I can also see the point of it becoming quite messy when more damage types are involved.
I'll think about a way to handle this differently
